//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Services/InteractionsService/Interactions/InputKeys/KeysInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Urd.Inputs
{
    public partial class @KeysInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @KeysInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeysInput"",
    ""maps"": [
        {
            ""name"": ""Keys"",
            ""id"": ""b8e184fd-d117-4a41-a624-f71f1e872fc1"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""74390472-fc9c-4058-909a-40c30ee21a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0fb910ca-abfd-4fd6-9283-7bfa77a19088"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Keys
            m_Keys = asset.FindActionMap("Keys", throwIfNotFound: true);
            m_Keys_Back = m_Keys.FindAction("Back", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Keys
        private readonly InputActionMap m_Keys;
        private List<IKeysActions> m_KeysActionsCallbackInterfaces = new List<IKeysActions>();
        private readonly InputAction m_Keys_Back;
        public struct KeysActions
        {
            private @KeysInput m_Wrapper;
            public KeysActions(@KeysInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Back => m_Wrapper.m_Keys_Back;
            public InputActionMap Get() { return m_Wrapper.m_Keys; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(KeysActions set) { return set.Get(); }
            public void AddCallbacks(IKeysActions instance)
            {
                if (instance == null || m_Wrapper.m_KeysActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_KeysActionsCallbackInterfaces.Add(instance);
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }

            private void UnregisterCallbacks(IKeysActions instance)
            {
                @Back.started -= instance.OnBack;
                @Back.performed -= instance.OnBack;
                @Back.canceled -= instance.OnBack;
            }

            public void RemoveCallbacks(IKeysActions instance)
            {
                if (m_Wrapper.m_KeysActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IKeysActions instance)
            {
                foreach (var item in m_Wrapper.m_KeysActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_KeysActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public KeysActions @Keys => new KeysActions(this);
        public interface IKeysActions
        {
            void OnBack(InputAction.CallbackContext context);
        }
    }
}
